## Упражнения по NumPy
Все задачи здесь можно (и нужно) выполнить только методами numpy без использования циклов.
Задания не обязательные и не на оценку, они нужны только для того, чтобы помочь вам получше разобраться с NumPy.

In [43]:
import numpy as np
np.random.seed(42)


### Линейные операторы
Даны два линейных оператора. Создайте новый оператор, который будет их композицией.

In [46]:
a = np.random.randn(8, 8)
b = np.random.randn(8, 8)
c = a @ b
d = b @ a
c

array([[-3.08613323,  2.72119979, -4.26496508,  2.06459517, -6.11689233,
        -3.32004624, -3.98910267,  5.81669579],
       [-2.89842685, -2.89745573, -0.14780357,  4.05578447,  3.240371  ,
         4.17245721,  4.4862378 , -2.93934185],
       [ 0.24147896,  0.0449541 , -2.80686623,  2.23304629, -0.68743858,
        -1.27577316,  2.1586844 ,  2.07545644],
       [ 1.01204775, -3.42135141,  3.80271189, -2.98220319, -2.57975746,
        -0.26623774, -0.54462689, -4.61967443],
       [-0.5911613 ,  0.72191497, -1.18410091,  3.62788959,  1.8926207 ,
         0.72205099,  1.75453014,  0.28076253],
       [-1.08503774, -0.57842538,  0.11566263,  0.74702562, -1.80179261,
        -0.4216256 ,  1.65600289,  0.96821806],
       [ 0.59658173, -0.51430395,  3.81225468, -1.66289117, -1.98381391,
        -0.56066586, -2.45188313, -2.42005518],
       [-0.15788877, -0.27134394, -0.43294344, -0.31001399, -1.50425478,
        -0.92283956,  3.20047188, -0.84536119]])

Примените созданный оператор из предыдущего пункта к вектору.

In [49]:
v = np.random.randn(8)
u = c @ v
u

array([ 7.48000951,  3.31710109, -3.40715447,  2.55130551, -1.6411234 ,
        0.75488838,  2.80480342, -2.79676037])

Посчитайте обратный оператор для оператора $c$ и примените его к вектору $u$ 

In [50]:
c_inv = np.linalg.inv(c)
u_inv = c_inv @ u
u_inv

array([-1.59442766, -0.59937502,  0.0052437 ,  0.04698059, -0.45006547,
        0.62284993, -1.06762043, -0.14237949])

### Создание и изменение массивов
Создайте верхнетреугольную матрицу со случайными элементами.

In [54]:
a = np.array(np.random.randn(8, 8))
np.triu(a) # верхняя треугольная матрица размером 3x3

array([[-0.86041337, -0.38455554,  1.00629281, -0.57689187,  0.83569211,
        -1.12970685,  0.52980418,  1.44156862],
       [ 0.        , -0.79689526,  0.57707213, -0.20304539,  0.37114587,
        -0.60398519,  0.08658979, -0.15567724],
       [ 0.        ,  0.        ,  0.33760266, -0.41187697, -0.48760622,
        -0.43255819,  0.39445214, -0.42098448],
       [ 0.        ,  0.        ,  0.        , -0.32602353,  1.20121392,
        -0.40807537, -2.03812454, -1.00808631],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.32692737,
        -0.21910053,  0.82940558, -2.21113531],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.41528791,  0.63278187,  2.27069286],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.07156624, -0.47765745],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.37730049]])

Создайте случайную матрицу перестановки.

In [77]:
i = np.identity(10)
rr = np.arange(10)
np.random.shuffle(rr)
np.take(i, rr, axis=1)

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Дан случайный массив. Сделайте циклический сдвиг на 2 вдоль второй оси двумя разными способами.

In [65]:
np.random.randint(0, 2, size=(9,9))

array([[1, 1, 0, 1, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 1, 0, 0, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 0, 1],
       [0, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0]])

Дан случайный массив. Двумя разными способами приравняйте в нем все элементы меньше 0 к 0.

In [21]:
a = np.random.randn(8, 8, 8)
a1 = None
a2 = None

Даны два набора точек в восьмимерном пространстве. Посчитайте матрицу евклидовых расстояний между всеми парами точек из первого и второго наборов.

In [22]:
a = np.random.randn(16, 8)
b = np.random.randn(32, 8)
a_b_dist = None

Используя посчитанную матрицу расстояний найдите для каждой точки из набора $a$ ближайшую точку из набора $b$. Вывидите индексы точек и сами точки.