## Pandas

In [2]:
import pandas

# Reading csv
dataframe = pandas.read_csv("cancer.csv", header=1)

# Converting dataframe to list
dataframe.values.tolist()[:2]

[['M',
  20.57,
  17.77,
  132.9,
  1326.0,
  0.08474,
  0.07864,
  0.0869,
  0.07017,
  0.1812,
  0.05667,
  0.5435,
  0.7339,
  3.398,
  74.08,
  0.005225,
  0.01308,
  0.0186,
  0.0134,
  0.01389,
  0.003532,
  24.99,
  23.41,
  158.8,
  1956.0,
  0.1238,
  0.1866,
  0.2416,
  0.186,
  0.275,
  0.08902],
 ['M',
  19.69,
  21.25,
  130.0,
  1203.0,
  0.1096,
  0.1599,
  0.1974,
  0.1279,
  0.2069,
  0.05999,
  0.7456,
  0.7869,
  4.585,
  94.03,
  0.00615,
  0.04006,
  0.03832,
  0.02058,
  0.0225,
  0.004571,
  23.57,
  25.53,
  152.5,
  1709.0,
  0.1444,
  0.4245,
  0.4504,
  0.243,
  0.3613,
  0.08758]]

## NumPy

### Создание массивов

In [24]:
import numpy as np
np.random.seed(42)

# Converting from and to list
vector = [1, 2, 3]
np_vector = np.array(vector)
vector = np_vector.tolist()
matrix = [[1, 2, 3], [4, 5, 6]]
np_matrix = np.array(matrix)
matrix = np_matrix.tolist()

In [16]:
# Primitives
ones = np.ones((4, 3, 2))
zeros = np.zeros((2, 3, 4))
np_range = np.arange(1, 6)
np_range = np.arange(1, 6, 0.5)
np_linspace = np.linspace(0, 1, 4)
eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
# Random
normal_distribution = np.random.randn(2, 3)
uniform_distribution = np.random.random((2, 3))
integers = np.random.randint(1, 3, (2, 3))

### Индексирование

In [30]:
# Slicing
normal_distribution = np.random.randn(6, 8)
print(normal_distribution)
# normal_distribution[1, 1]
# normal_distribution[:, 1] # 2nd column
# normal_distribution[::-1, 1]
# normal_distribution[::2, 1]
# normal_distribution[1, :]
# normal_distribution[1]
#
# # Берем значения по маске
# normal_distribution[(normal_distribution > 0)] # 1d!!!
# normal_distribution[np.random.randn(6) > 0] # 2d!!!
normal_distribution[:, np.random.randn(8) > 0] # 2d!!!
#
# # Берем определенные индексы
# ids = np.arange(0, 6, 2)
# normal_distribution[ids]

[[-0.92693047 -0.05952536 -3.24126734 -1.02438764 -0.25256815 -1.24778318
   1.6324113  -1.43014138]
 [-0.44004449  0.13074058  1.44127329 -1.43586215  1.16316375  0.01023306
  -0.98150865  0.46210347]
 [ 0.1990597  -0.60021688  0.06980208 -0.3853136   0.11351735  0.66213067
   1.58601682 -1.2378155 ]
 [ 2.13303337 -1.9520878  -0.1517851   0.58831721  0.28099187 -0.62269952
  -0.20812225 -0.49300093]
 [-0.58936476  0.8496021   0.35701549 -0.6929096   0.89959988  0.30729952
   0.81286212  0.62962884]
 [-0.82899501 -0.56018104  0.74729361  0.61037027 -0.02090159  0.11732738
   1.2776649  -0.59157139]]


array([[-0.92693047, -1.02438764, -0.25256815, -1.24778318,  1.6324113 ,
        -1.43014138],
       [-0.44004449, -1.43586215,  1.16316375,  0.01023306, -0.98150865,
         0.46210347],
       [ 0.1990597 , -0.3853136 ,  0.11351735,  0.66213067,  1.58601682,
        -1.2378155 ],
       [ 2.13303337,  0.58831721,  0.28099187, -0.62269952, -0.20812225,
        -0.49300093],
       [-0.58936476, -0.6929096 ,  0.89959988,  0.30729952,  0.81286212,
         0.62962884],
       [-0.82899501,  0.61037027, -0.02090159,  0.11732738,  1.2776649 ,
        -0.59157139]])

In [31]:
# Operations with slices
normal_distribution = np.random.randn(6, 4)
print(normal_distribution)
normal_distribution[:, 1] = 10
print(normal_distribution)

[[ 0.68195297 -0.31026676  0.32416635 -0.13014305]
 [ 0.09699596  0.59515703 -0.81822068  2.09238728]
 [-1.00601738 -1.21418861  1.15811087  0.79166269]
 [ 0.62411982  0.62834551 -0.01224677 -0.89725437]
 [ 0.07580456 -0.67716171  0.97511973 -0.14705738]
 [-0.8254972  -0.32138584  0.41293145 -0.56372455]]
[[ 0.68195297 10.          0.32416635 -0.13014305]
 [ 0.09699596 10.         -0.81822068  2.09238728]
 [-1.00601738 10.          1.15811087  0.79166269]
 [ 0.62411982 10.         -0.01224677 -0.89725437]
 [ 0.07580456 10.          0.97511973 -0.14705738]
 [-0.8254972  10.          0.41293145 -0.56372455]]


### Математические операции

In [32]:
# Среднее
a = np.random.randn(8, 8)
print(a)
print(np.mean(a))
print(a.mean())
print(a.mean(-1))

[[-0.8222204   0.24368721  0.24496657 -0.50694318 -0.47103831  0.23204994
  -1.44808434 -1.40746377]
 [-0.71844422 -0.21344715  0.31090757  1.47535622  0.85765962 -0.15993853
  -0.01901621 -1.00252936]
 [-0.01851314 -0.28865864  0.32271856 -0.82723094  0.51934651  1.53273891
  -0.10876015  0.40171172]
 [ 0.69014399 -0.40122047  0.22409248  0.0125924   0.0976761  -0.77300978
   0.02451017  0.49799829]
 [ 1.45114361  0.95927083  2.15318246 -0.76734756  0.87232064  0.18334201
   2.18980293 -0.80829829]
 [-0.83972184 -0.59939265 -2.12389572 -0.52575502 -0.75913266  0.15039379
   0.34175598  1.87617084]
 [ 0.95042384 -0.57690366 -0.89841467  0.49191917 -1.32023321  1.83145877
   1.17944012 -0.46917565]
 [-1.71313453  1.35387237 -0.11453985  1.23781631 -1.59442766 -0.59937502
   0.0052437   0.04698059]]
0.03228793190581159
0.03228793190581159
[-0.49188078  0.06631849  0.19166911  0.0465979   0.77917708 -0.30994716
  0.14856434 -0.17219551]


In [37]:
# Максимум
a = np.random.randn(8, 8)
print(a)
print(np.max(a))
print(a.max())
print(a.max(-1)) # max из каждого array

[[-0.57366201 -0.54685894 -0.03275327 -0.54342477 -0.71284578  0.10643023
  -0.25497722  1.50399299]
 [-2.65096981  1.09150685  1.24608519 -2.07339023 -0.34268759 -0.37144087
  -1.40751169 -0.77781669]
 [-1.11057585  1.75227044  0.93567839  1.27155509  0.72167206 -1.12905177
  -0.52452027  0.48937456]
 [-1.22212781  0.71299843 -0.2403254  -0.37482081  0.71095997  0.44426331
  -0.36096617  1.1593298 ]
 [-1.08106333  0.61593561  0.59310126 -0.30954644  0.32613302 -1.25111358
   0.92402702 -0.18490214]
 [-0.52272302  1.04900923 -0.70434369 -1.4084613  -1.55662917  0.60600995
  -1.28042935  1.75479418]
 [-2.08192941  1.69645637  0.21101747 -0.09671311 -0.54491909  0.39913611
  -0.0376347   1.10330188]
 [ 0.11422765  0.15030176 -0.36361221 -0.05694562  0.30780177 -1.71016839
  -1.34818542  0.74326409]]
1.7547941819843647
1.7547941819843647
[1.50399299 1.24608519 1.75227044 1.1593298  0.92402702 1.75479418
 1.69645637 0.74326409]


In [36]:
# Argmax
a = np.random.randn(8, 8)
print(a)
print(np.argmax(a)) # Position in flattened array
print(a.argmax(-1)) # max indices в каждом array

[[-0.26987494 -0.97876372 -0.44429326  0.37730049  0.75698862 -0.92216532
   0.86960592  1.35563786]
 [ 0.4134349   1.87679581 -0.7737892  -1.2446547  -1.77872025  1.49604431
   0.65436566 -0.05558467]
 [ 0.27996863 -1.12548905  2.44575198  0.12922118  0.10939479  0.72576662
   0.48100923  0.22388402]
 [-0.79047446  0.47146836  1.8820245   1.34542005  1.59318663 -0.51121568
  -0.98960482 -0.12578692]
 [ 0.05572491  1.09419152 -1.69246463  1.52955032 -0.1580079  -0.42688107
  -1.01210438 -1.65485667]
 [ 0.82317058  0.07331797 -1.2899609  -1.29507877 -0.3357847   1.66902153
  -0.25959135 -1.50314295]
 [-0.24574306 -0.27272357 -2.69688664 -0.05429487 -0.23093453  0.69620636
   1.84895609  1.12656503]
 [-0.26888869 -1.10652591  2.5733598   0.05921843  0.01392929 -0.02412509
   0.19808476 -0.14436041]]
58
[7 1 2 2 3 5 6 2]


In [11]:
# Get unique elements
np.unique(np.random.randint(1, 100, 1000), return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
        86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([10,  8,  6, 14, 17,  7,  8, 16,  5, 11, 10, 11, 10,  8, 11, 16,  5,
         8,  8, 15,  8,  5,  9, 10, 14,  7, 21, 11,  7, 13,  6,  8, 10,  8,
        11,  5, 13,  6, 15,  5, 15, 14, 12, 13, 11, 10, 12, 11, 13,  8,  5,
        15, 10,  4, 11, 11, 11,  5,  8,  8,  9, 18, 16,  6, 12, 11,  7,  5,
         8, 15, 13,  6, 12, 10,  9, 11, 10,  8,  7,  7,  9,  6,  9, 14, 15,
         8,  8,  8, 11,  7,  7, 10,  9,  7, 11, 10, 13, 16, 19]))

In [12]:
np_vector = np.random.randn(16)
np_matrix = np.random.randn(16, 16)

# Elementvise operations
np_vector * np_vector
np_vector - np_vector
np_vector + np_vector
np_vector / np_vector
np_matrix * np_vector
np_matrix - np_vector
np_matrix + np_vector
np_matrix / np_vector

# Tensor operations
np_vector.dot(np_vector) # Production
np_matrix.T # Transpose

array([[-1.66739089e+00,  1.31321502e+00,  7.80636270e-01,
        -6.84236961e-01, -1.99823745e+00,  1.04238423e+00,
        -1.35218123e-01, -1.75389436e-01,  1.32736126e+00,
        -1.61089738e-01, -1.01418711e+00, -2.94832064e+00,
        -1.56000484e-01, -1.12875999e+00, -7.04959908e-01,
         1.13710764e-01],
       [-1.23014752e+00,  3.51174233e-01, -9.93915132e-01,
         5.25732503e-01, -4.82208095e-01, -1.62050822e-01,
         7.04359978e-01,  5.57094175e-01, -1.79895489e+00,
        -6.57323983e-01, -1.53219604e+00, -1.98038913e-01,
        -5.37868186e-01,  4.89333223e-01, -1.58770940e-01,
        -3.22570192e-03],
       [-7.55434466e-01,  4.09479487e-01,  1.35321024e-01,
         1.40643553e+00,  1.50329236e+00,  1.13416709e+00,
         5.37068220e-01, -3.24539882e-01,  1.06079096e-01,
         1.55734103e+00, -3.31792961e-01, -1.73852545e-01,
         3.89999467e-01,  9.82268919e-01,  1.09553435e+00,
         7.10344844e-01],
       [ 6.13344447e-01,  1.35327794e

In [13]:
a = np.random.randn(8, 8)
print(np.linalg.norm(a))
print(np.linalg.norm(a, axis=-1))

7.442184278938985
[2.30844337 1.56362947 1.81985694 2.47725223 3.46624159 2.8722265
 2.9011083  3.07939212]


### Изменение размерности

In [14]:
# Shape
a = np.linspace(0, 1, 12)
print(a)
a = a.reshape((2, 6))
print(a)
a = a.reshape((-1, 3))
print(a)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
[[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545]
 [0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]]
[[0.         0.09090909 0.18181818]
 [0.27272727 0.36363636 0.45454545]
 [0.54545455 0.63636364 0.72727273]
 [0.81818182 0.90909091 1.        ]]


In [39]:
a = np.random.randn(4, 4)
b = np.random.randn(4, 4, 4)
a = np.expand_dims(a, 1)
a = np.broadcast_to(a, b.shape)
print(a)

[[[-0.43449623 -0.30917212  0.22213377 -0.47874862]
  [-0.43449623 -0.30917212  0.22213377 -0.47874862]
  [-0.43449623 -0.30917212  0.22213377 -0.47874862]
  [-0.43449623 -0.30917212  0.22213377 -0.47874862]]

 [[ 1.25575613 -0.8946073  -0.18687164 -0.43973106]
  [ 1.25575613 -0.8946073  -0.18687164 -0.43973106]
  [ 1.25575613 -0.8946073  -0.18687164 -0.43973106]
  [ 1.25575613 -0.8946073  -0.18687164 -0.43973106]]

 [[ 1.44697788  0.19655478  1.03184454 -1.48556037]
  [ 1.44697788  0.19655478  1.03184454 -1.48556037]
  [ 1.44697788  0.19655478  1.03184454 -1.48556037]
  [ 1.44697788  0.19655478  1.03184454 -1.48556037]]

 [[ 0.26705027  0.8896308   0.08228399  1.06548038]
  [ 0.26705027  0.8896308   0.08228399  1.06548038]
  [ 0.26705027  0.8896308   0.08228399  1.06548038]
  [ 0.26705027  0.8896308   0.08228399  1.06548038]]]
